name: physion
channels:
  - conda-forge
dependencies:
  - python=3.7.10
  - pip=21.1.2
  - mkl_fft=1.0.10
  - mkl=2019.3
  - tbb=2021.5.0
  - numpy=1.18.5
  - numba=0.48.0
  - scipy=1.6.3
  - scikit-learn=0.24.2
  - scikit-image=0.18.1
  - ruamel.yaml=0.17.21
  - ruamel=1.0
  - pathlib=1.0.1
  - matplotlib=3.4.2
  - jupyter=1.0.0
  - jupytext=1.14.0
  - pynwb=2.0.0
  - ffmpeg=5.0.1
  - pip:
    - pyqtdarktheme==1.2.1
    - pyqtgraph==0.12.1
    - psychopy==2021.1.1
    - opencv-python-headless==4.5.5.62
    - pygame==2.1.2
  - qt=5.9.6

